### ISSUE TITLE
CUDA编译错误

### ISSUE THREAD

**Issue by Polly2014** [dongdonghy/Detection-PyTorch-Notebook#11]
博主你好，我使用的pytorch版本为1.3.1，运行```sh make.sh```时碰到错误如下
```sh
running build_ext
skipping 'model/utils/bbox.c' Cython extension (up-to-date)
skipping 'pycocotools/_mask.c' Cython extension (up-to-date)
Compiling nms kernels by nvcc...
Traceback (most recent call last):
  File "build.py", line 4, in <module>
    from torch.utils.ffi import create_extension
  File "/home/polly/anaconda3/envs/FasterRCNN/lib/python3.7/site-packages/torch/utils/ffi/__init__.py", line 1, in <module>
    raise ImportError("torch.utils.ffi is deprecated. Please use cpp extensions instead.")
ImportError: torch.utils.ffi is deprecated. Please use cpp extensions instead.
Compiling roi pooling kernels by nvcc...
Traceback (most recent call last):
  File "build.py", line 4, in <module>
    from torch.utils.ffi import create_extension
  File "/home/polly/anaconda3/envs/FasterRCNN/lib/python3.7/site-packages/torch/utils/ffi/__init__.py", line 1, in <module>
    raise ImportError("torch.utils.ffi is deprecated. Please use cpp extensions instead.")
ImportError: torch.utils.ffi is deprecated. Please use cpp extensions instead.
Compiling roi align kernels by nvcc...
Traceback (most recent call last):
  File "build.py", line 4, in <module>
    from torch.utils.ffi import create_extension
  File "/home/polly/anaconda3/envs/FasterRCNN/lib/python3.7/site-packages/torch/utils/ffi/__init__.py", line 1, in <module>
    raise ImportError("torch.utils.ffi is deprecated. Please use cpp extensions instead.")
ImportError: torch.utils.ffi is deprecated. Please use cpp extensions instead.
Compiling roi crop kernels by nvcc...
Traceback (most recent call last):
  File "build.py", line 5, in <module>
    from torch.utils.ffi import create_extension
  File "/home/polly/anaconda3/envs/FasterRCNN/lib/python3.7/site-packages/torch/utils/ffi/__init__.py", line 1, in <module>
    raise ImportError("torch.utils.ffi is deprecated. Please use cpp extensions instead.")
ImportError: torch.utils.ffi is deprecated. Please use cpp extensions instead.
```
这个该如何解决呢，求教

**Comment by Polly2014** [comment]
> 博主你好，我使用的pytorch版本为1.3.1，运行`sh make.sh`时碰到错误如下
> 
> ```shell
> running build_ext
> skipping 'model/utils/bbox.c' Cython extension (up-to-date)
> skipping 'pycocotools/_mask.c' Cython extension (up-to-date)
> Compiling nms kernels by nvcc...
> Traceback (most recent call last):
>   File "build.py", line 4, in <module>
>     from torch.utils.ffi import create_extension
>   File "/home/polly/anaconda3/envs/FasterRCNN/lib/python3.7/site-packages/torch/utils/ffi/__init__.py", line 1, in <module>
>     raise ImportError("torch.utils.ffi is deprecated. Please use cpp extensions instead.")
> ImportError: torch.utils.ffi is deprecated. Please use cpp extensions instead.
> Compiling roi pooling kernels by nvcc...
> Traceback (most recent call last):
>   File "build.py", line 4, in <module>
>     from torch.utils.ffi import create_extension
>   File "/home/polly/anaconda3/envs/FasterRCNN/lib/python3.7/site-packages/torch/utils/ffi/__init__.py", line 1, in <module>
>     raise ImportError("torch.utils.ffi is deprecated. Please use cpp extensions instead.")
> ImportError: torch.utils.ffi is deprecated. Please use cpp extensions instead.
> Compiling roi align kernels by nvcc...
> Traceback (most recent call last):
>   File "build.py", line 4, in <module>
>     from torch.utils.ffi import create_extension
>   File "/home/polly/anaconda3/envs/FasterRCNN/lib/python3.7/site-packages/torch/utils/ffi/__init__.py", line 1, in <module>
>     raise ImportError("torch.utils.ffi is deprecated. Please use cpp extensions instead.")
> ImportError: torch.utils.ffi is deprecated. Please use cpp extensions instead.
> Compiling roi crop kernels by nvcc...
> Traceback (most recent call last):
>   File "build.py", line 5, in <module>
>     from torch.utils.ffi import create_extension
>   File "/home/polly/anaconda3/envs/FasterRCNN/lib/python3.7/site-packages/torch/utils/ffi/__init__.py", line 1, in <module>
>     raise ImportError("torch.utils.ffi is deprecated. Please use cpp extensions instead.")
> ImportError: torch.utils.ffi is deprecated. Please use cpp extensions instead.
> ```
> 
> 这个该如何解决呢，求教

我看网上的方法，将```from torch.utils.ffi import create_extension```替换为```from torch.utils.cpp_extension import BuildExtension```，之后又报了新的错误如下
```sh
(FasterRCNN) polly@ict:~/GitHub_Workspace/Detection-PyTorch-Notebook/chapter4/faster-rcnn-pytorch/lib$ sh make.sh
running build_ext
skipping 'model/utils/bbox.c' Cython extension (up-to-date)
skipping 'pycocotools/_mask.c' Cython extension (up-to-date)
Compiling nms kernels by nvcc...
Including CUDA code.
/home/polly/GitHub_Workspace/Detection-PyTorch-Notebook/chapter4/faster-rcnn-pytorch/lib/model/nms
['/home/polly/GitHub_Workspace/Detection-PyTorch-Notebook/chapter4/faster-rcnn-pytorch/lib/model/nms/src/nms_cuda_kernel.cu.o']
Traceback (most recent call last):
  File "build.py", line 34, in <module>
    extra_objects=extra_objects
  File "/home/polly/anaconda3/envs/FasterRCNN/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 234, in __init__
    super(BuildExtension, self).__init__(*args, **kwargs)
  File "/home/polly/anaconda3/envs/FasterRCNN/lib/python3.7/site-packages/setuptools/__init__.py", line 163, in __init__
    _Command.__init__(self, dist)
  File "/home/polly/anaconda3/envs/FasterRCNN/lib/python3.7/distutils/cmd.py", line 57, in __init__
    raise TypeError("dist must be a Distribution instance")
TypeError: dist must be a Distribution instance
...
```
求教这个该怎么解决

**Comment by Polly2014** [comment]
> 博主你好，我使用的pytorch版本为1.3.1，运行`sh make.sh`时碰到错误如下
> 
> ```shell
> running build_ext
> skipping 'model/utils/bbox.c' Cython extension (up-to-date)
> skipping 'pycocotools/_mask.c' Cython extension (up-to-date)
> Compiling nms kernels by nvcc...
> Traceback (most recent call last):
>   File "build.py", line 4, in <module>
>     from torch.utils.ffi import create_extension
>   File "/home/polly/anaconda3/envs/FasterRCNN/lib/python3.7/site-packages/torch/utils/ffi/__init__.py", line 1, in <module>
>     raise ImportError("torch.utils.ffi is deprecated. Please use cpp extensions instead.")
> ImportError: torch.utils.ffi is deprecated. Please use cpp extensions instead.
> Compiling roi pooling kernels by nvcc...
> Traceback (most recent call last):
>   File "build.py", line 4, in <module>
>     from torch.utils.ffi import create_extension
>   File "/home/polly/anaconda3/envs/FasterRCNN/lib/python3.7/site-packages/torch/utils/ffi/__init__.py", line 1, in <module>
>     raise ImportError("torch.utils.ffi is deprecated. Please use cpp extensions instead.")
> ImportError: torch.utils.ffi is deprecated. Please use cpp extensions instead.
> Compiling roi align kernels by nvcc...
> Traceback (most recent call last):
>   File "build.py", line 4, in <module>
>     from torch.utils.ffi import create_extension
>   File "/home/polly/anaconda3/envs/FasterRCNN/lib/python3.7/site-packages/torch/utils/ffi/__init__.py", line 1, in <module>
>     raise ImportError("torch.utils.ffi is deprecated. Please use cpp extensions instead.")
> ImportError: torch.utils.ffi is deprecated. Please use cpp extensions instead.
> Compiling roi crop kernels by nvcc...
> Traceback (most recent call last):
>   File "build.py", line 5, in <module>
>     from torch.utils.ffi import create_extension
>   File "/home/polly/anaconda3/envs/FasterRCNN/lib/python3.7/site-packages/torch/utils/ffi/__init__.py", line 1, in <module>
>     raise ImportError("torch.utils.ffi is deprecated. Please use cpp extensions instead.")
> ImportError: torch.utils.ffi is deprecated. Please use cpp extensions instead.
> ```
> 
> 这个该如何解决呢，求教

我看网上的方法，将```from torch.utils.ffi import create_extension```替换为```from torch.utils.cpp_extension import BuildExtension```，之后又报了新的错误如下
```sh
(FasterRCNN) polly@ict:~/GitHub_Workspace/Detection-PyTorch-Notebook/chapter4/faster-rcnn-pytorch/lib$ sh make.sh
running build_ext
skipping 'model/utils/bbox.c' Cython extension (up-to-date)
skipping 'pycocotools/_mask.c' Cython extension (up-to-date)
Compiling nms kernels by nvcc...
Including CUDA code.
/home/polly/GitHub_Workspace/Detection-PyTorch-Notebook/chapter4/faster-rcnn-pytorch/lib/model/nms
['/home/polly/GitHub_Workspace/Detection-PyTorch-Notebook/chapter4/faster-rcnn-pytorch/lib/model/nms/src/nms_cuda_kernel.cu.o']
Traceback (most recent call last):
  File "build.py", line 34, in <module>
    extra_objects=extra_objects
  File "/home/polly/anaconda3/envs/FasterRCNN/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 234, in __init__
    super(BuildExtension, self).__init__(*args, **kwargs)
  File "/home/polly/anaconda3/envs/FasterRCNN/lib/python3.7/site-packages/setuptools/__init__.py", line 163, in __init__
    _Command.__init__(self, dist)
  File "/home/polly/anaconda3/envs/FasterRCNN/lib/python3.7/distutils/cmd.py", line 57, in __init__
    raise TypeError("dist must be a Distribution instance")
TypeError: dist must be a Distribution instance
...
```
求教这个该怎么解决

**Comment by zhangyl660** [comment]
解决了吗？我也遇到了同样的问题

**Comment by Tlntin** [comment]
https://github.com/cagdasbas/faster-rcnn.pytorch/tree/pytorch-1.11
