### ISSUE TITLE
环境配置成功，代码跑不通

### ISSUE THREAD

**Issue by FreeZhang96** [dongdonghy/Detection-PyTorch-Notebook#9]
Traceback (most recent call last):
  File "/home/zhangfei/Code/Detection-PyTorch-Notebook-master/chapter4/faster-rcnn-pytorch/test_net.py", line 28, in <module>
    from model.nms.nms_wrapper import nms
  File "/home/zhangfei/Code/Detection-PyTorch-Notebook-master/chapter4/faster-rcnn-pytorch/lib/model/nms/nms_wrapper.py", line 10, in <module>
    from model.nms.nms_gpu import nms_gpu
  File "/home/zhangfei/Code/Detection-PyTorch-Notebook-master/chapter4/faster-rcnn-pytorch/lib/model/nms/nms_gpu.py", line 4, in <module>
    from ._ext import nms
  File "/home/zhangfei/Code/Detection-PyTorch-Notebook-master/chapter4/faster-rcnn-pytorch/lib/model/nms/_ext/nms/__init__.py", line 3, in <module>
    from ._nms import lib as _lib, ffi as _ffi
ImportError: /home/zhangfei/Code/Detection-PyTorch-Notebook-master/chapter4/faster-rcnn-pytorch/lib/model/nms/_ext/nms/_nms.so: undefined symbol: __cudaRegisterFatBinaryEnd

本人电脑显卡为RTX2060，没有记错的话只支持cuda10.0以上的版本，我安装了cuda10.2，pytorch0.4.0，验证安装成功，但是代码跑不通，求解。

**Comment by dongdonghy** [comment]
Hi，有修改arch，并重新编译NMS模块吗？

**Comment by FreeZhang96** [comment]
修改过了

**Comment by dongdonghy** [comment]
pytorch0.4.0最高支持cuda9，你可以用简单的tensor.cuda()来验证下该pytorch在该cuda下是否可用。如果不行，可以使用pytorch1.*版本来跑一下，有问题我们再解决。

**Comment by FreeZhang96** [comment]
cuda可用，我的问题在于电脑显卡是RTX2060的，好像只支持cuda10以上

**Comment by dongdonghy** [comment]
cuda本身肯定没问题，可以试下该pytorch能不能调用这个版本的cuda，我估计是该pytorch版本与该cuda版本不兼容。如果不兼容，使用高版本的pytorch吧。
